### ISSUE TITLE
npm WARN deprecated

### ISSUE THREAD

**Issue by hbo-lambda** [saleor/saleor-platform#108]
[![](https://read-code.oss-cn-beijing.aliyuncs.com/20210721163855.png)](url)
why? I tried many methods but can't slove this problem finally

**Comment by frediian** [comment]
What os are u using?

See the docke-compose and the docker compose dev
The version of node is the problem, review the file at the first line

If you choose the branch master, you need node 14
If choose branch stable 2.x.x, you need node 10
