### ISSUE TITLE
Product description is not saved from dashboard

### ISSUE THREAD

**Issue by firvida** [saleor/saleor-platform#109]
Whenever I try to edit a product description it is not saved in the database.

Steps to reproduce

```
cd saleor-platform

docker-compose run --rm api python3 manage.py migrate
docker-compose run --rm api python3 manage.py collectstatic --noinput
docker-compose run --rm api python3 manage.py populatedb
docker-compose run --rm api python3 manage.py createsuperuser

docker-compose up -d
```

Then enter in the admin at http://127.0.0.1:9000 find "Carrot Juice" product in catalog and change the description. Save it.
Now you can run. 

```
docker-compose exec db psql -U saleor -c "select description from product_product where name ilike 'Carrot Juice'";
```

IMHO here you should get the text that you entered previously as the description, but instead what I get is:

"Improve your eyesight the natural way with 100% pure, squeezed carrot juice. The sweet, orange nectar of Mother Earth."

which is the default text for that field in the populate db script. Can someone give me a hint on how to get over this error???

**Comment by lkostrowski** [comment]
Hi, it's a little stale, so I'm closing. Please update your Saleor setup and report a new issue if you face any problems
