### ISSUE TITLE
Run saleor 3 locally

### ISSUE THREAD

**Issue by jaekim0908** [saleor/saleor-platform#115]
Hi,

Is there any instructions to run saleor 3 locally? I want to test out multi-channel functionality in 3.0.

Thanks,
Jae.

**Comment by haneef-photon** [comment]
I followed the following steps:

1. Clone the repo from https://github.com/saleor/saleor-platform.git
2. **Important: ** Check out the version 3.0 branches. This are my versions that I used
![image](https://user-images.githubusercontent.com/81955814/149990540-e336577f-98a9-44bf-8bec-380a86dd1393.png)
3. Rest of the steps from installation guide work properly from here: https://docs.saleor.io/docs/3.0/developer/installation

**Please Note: ** After following these steps, I am able to successfully access saleor API, dashboard, mailhog on their respective URLs but not able to access storefront on port 3000
