### ISSUE TITLE
HOW TO CHANGE SUB MODULES BRANCH TO 3.0 OR 3.1 TO DEPLOY LATEST VERSION!!

### ISSUE THREAD

**Issue by emrebyimrn** [saleor/saleor-platform#117]
Hello there,
can anyone help me to change the submodule brach from 2.11 to 3.0 or 3.1.

**Comment by vhscom** [comment]
Hi Imran. Have you considered asking in the [Saleor community](https://saleor.io/open-source/#community) to help keep GitHub issues focused on development activities?

**Comment by vhscom** [comment]
Have you considered asking in the [Saleor community](https://saleor.io/open-source/#community)

**Comment by vhscom** [comment]
Have you considered asking in the [Saleor community](https://saleor.io/open-source/#community)?

**Comment by krzysztofwolski** [comment]
The repository has been updated to 3.1.
There's also an updated 3.0 branch.

**Comment by vhscom** [comment]
Thanks for the heads-up @krzysztofwolski
