### ISSUE TITLE
Replace Django with FastAPI

### ISSUE THREAD

**Issue by JimScope** [saleor/saleor-platform#122]
It is possible to replace Django with FastAPI. Performance is superior.

**Comment by krzysztofwolski** [comment]
Saleor was created way before Fast API and Django is a good framework after all :). Migrating such a large codebase is not a light task, but are experimenting with incorporating async features into the project. Can't tell if Fast API will be our final choice, but so far we are happy with using it in our other projects. For sure it's one of the favorite candidates for a framework change.
