### ISSUE TITLE
storefront and dashboard only access from localhost

### ISSUE THREAD

**Issue by sadegh-khan** [saleor/saleor-platform#125]
why dashborad and storefront access only on localhost:3000 and localhost:900, 
my ip address is 172.16.1.54 and i want to access to store front and dashboard from another pc, but only can access to backend (172.16.1.54:8000) not (172.16.1.54:3000) and (172.16.1.54:9000)

i changed docker-compose.yml to below but not work,
    environment:
      - JAEGER_AGENT_HOST=jaeger
      **- STOREFRONT_URL=http://localhost:3000/  to  0.0.0.0:3000/**
      **- DASHBOARD_URL=http://localhost:9000/  to 0.0.0.0:9000/**

**Comment by AhmadManzoor** [comment]
make sure your port is open in your networking i.e for aws check your security group and add 9000 and 3000 ports in inbound rules

**Comment by magul** [comment]
Hi @sadegh-khan ,

although what you want to achieve is possible, we don't intend to deliver that as (based on our `README`):

>  Keep in mind this repository is for local development only and is not meant to be deployed on any production environment! If you're not a developer and just want to try out Saleor you can check our [live demo](https://demo.saleor.io/).

Closing that one as wont fix.
