### ISSUE TITLE
Saleor API does not work when build on Apple M1

### ISSUE THREAD

**Issue by koradon** [saleor/saleor-platform#147]
There is a problem with `libpq` on Apple M1 silicone.

When I tried to run migrations 
```
$ docker-compose run --rm api python3 manage.py migrate
```
I got error like this:
```
pg_connect(): Unable to connect to PostgreSQL server: SCRAM authentication requires libpq version 10 or above.
```

**TLDR**
Force building on x86 architecture
```
export DOCKER_DEFAULT_PLATFORM=linux/amd64
```

**Explanation**
There are a few solutions to this described in [here](https://stackoverflow.com/questions/62807717/how-can-i-solve-postgresql-scram-authentifcation-problem) and [here](https://stackoverflow.com/questions/65612411/forcing-docker-to-use-linux-amd64-platform-by-default-on-macos/69636473#69636473)

I think that some mention in README would be great.

**Comment by tiendq** [comment]
Using `export DOCKER_DEFAULT_PLATFORM=linux/amd64` caused another issue for me, `npm install` step hanged forever :(

**Comment by lkostrowski** [comment]
Hi, I tested it with M1 Pro and I don't face any issues. 

`npm` step should be also resolved, frontend repositories have been updated a lot. 

Please open new issue if you face any problems
