### ISSUE TITLE
Issue when running migration command 

### ISSUE THREAD

**Issue by proalaa** [saleor/saleor-platform#150]
Hi guys 

I get this issue when runing `docker-compose run --rm api python3 manage.py migrate`

> Creating saleor-platform_db_1 ... done
> Creating saleor-platform_api_run ... done
> WARNING saleor.core.jwt_manager RSA_PRIVATE_KEY is missing. Using temporary key for local development with DEBUG mode. [PID:1:MainThread]
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
>     self.connect()
>   File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 33, in inner
>     return func(*args, **kwargs)
>   File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 200, in connect
>     self.connection = self.get_new_connection(conn_params)
>   File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 33, in inner
>     return func(*args, **kwargs)
>   File "/usr/local/lib/python3.9/site-packages/django/db/backends/postgresql/base.py", line 187, in get_new_connection
>     connection = Database.connect(**conn_params)
>   File "/usr/local/lib/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect
>     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
> psycopg2.OperationalError: could not translate host name "db" to address: Name or service not known
> 
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "/app/manage.py", line 10, in <module>
>     execute_from_command_line(sys.argv)
>   File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
>     utility.execute()
>   File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 413, in execute
>     self.fetch_command(subcommand).run_from_argv(self.argv)
>   File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 354, in run_from_argv
>     self.execute(*args, **cmd_options)
>   File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 398, in execute
>     output = self.handle(*args, **options)
>   File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 89, in wrapped
>     res = handle_func(*args, **kwargs)
>   File "/usr/local/lib/python3.9/site-packages/django/core/management/commands/migrate.py", line 75, in handle
>     self.check(databases=[database])
>   File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 419, in check
>     all_issues = checks.run_checks(
>   File "/usr/local/lib/python3.9/site-packages/django/core/checks/registry.py", line 76, in run_checks
>     new_errors = check(app_configs=app_configs, databases=databases)
>   File "/usr/local/lib/python3.9/site-packages/django/core/checks/model_checks.py", line 34, in check_all_models
>     errors.extend(model.check(**kwargs))
>   File "/usr/local/lib/python3.9/site-packages/django/db/models/base.py", line 1303, in check
>     *cls._check_indexes(databases),
>   File "/usr/local/lib/python3.9/site-packages/django/db/models/base.py", line 1695, in _check_indexes
>     connection.features.supports_covering_indexes or
>   File "/usr/local/lib/python3.9/site-packages/django/utils/functional.py", line 48, in __get__
>     res = instance.__dict__[self.name] = self.func(instance)
>   File "/usr/local/lib/python3.9/site-packages/django/db/backends/postgresql/features.py", line 92, in is_postgresql_11
>     return self.connection.pg_version >= 110000
>   File "/usr/local/lib/python3.9/site-packages/django/utils/functional.py", line 48, in __get__
>     res = instance.__dict__[self.name] = self.func(instance)
>   File "/usr/local/lib/python3.9/site-packages/django/db/backends/postgresql/base.py", line 329, in pg_version
>     with self.temporary_connection():
>   File "/usr/local/lib/python3.9/contextlib.py", line 119, in __enter__
>     return next(self.gen)
>   File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 603, in temporary_connection
>     with self.cursor() as cursor:
>   File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 33, in inner
>     return func(*args, **kwargs)
>   File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 259, in cursor
>     return self._cursor()
>   File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 235, in _cursor
>     self.ensure_connection()
>   File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 33, in inner
>     return func(*args, **kwargs)
>   File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
>     self.connect()
>   File "/usr/local/lib/python3.9/site-packages/django/db/utils.py", line 90, in __exit__
>     raise dj_exc_value.with_traceback(traceback) from exc_value
>   File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
>     self.connect()
>   File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 33, in inner
>     return func(*args, **kwargs)
>   File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 200, in connect
>     self.connection = self.get_new_connection(conn_params)
>   File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 33, in inner
>     return func(*args, **kwargs)
>   File "/usr/local/lib/python3.9/site-packages/django/db/backends/postgresql/base.py", line 187, in get_new_connection
>     connection = Database.connect(**conn_params)
>   File "/usr/local/lib/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect
>     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
> django.db.utils.OperationalError: could not translate host name "db" to address: Name or service not known

> 

> ERROR: 1

![image](https://user-images.githubusercontent.com/41290898/168064204-7575365e-1328-40b7-89fb-6f5415700027.png)

this prevent me continuing to install the platform , so please any help

**Comment by sahanljc** [comment]
Hi guys,

I'm seeing the same issue here. Any update about this?

**Comment by sahanljc** [comment]
Just in case if you are still seeing the error, I found that in my case the `db` service was restarting. That was why the service could not be discovered.

**Comment by rafalp** [comment]
This error means that database service failed to start, or it started but PostgreSQL service inside docker is not accepting connections.

To debug this run `db` service:

```
docker-compose up db
```

In my case I've got following error:

```
db_1                | PostgreSQL Database directory appears to contain a database; Skipping initialization
db_1                |
db_1                | 2022-08-24 13:24:27.573 UTC [1] FATAL:  database files are incompatible with server
db_1                | 2022-08-24 13:24:27.573 UTC [1] DETAIL:  The data directory was initialized by PostgreSQL version 11, which is not compatible with this version 13.8.
saleor-platform_db_1 exited with code 1
```

Which means that saleor-db volume was created previously by older PostgreSQL version (likely in older version of saleor-platform).
