### ISSUE TITLE
docker-compose error

### ISSUE THREAD

**Issue by tantubufan** [saleor/saleor-platform#153]
container_linux.go:290: starting container process caused "process_linux.go:259: applying cgroup configuration for process caused \"Cannot set property TasksAccounting, or unknown property.\""
ERROR: Service 'dashboard' failed to build: oci runtime error: container_linux.go:290: starting container process caused "process_linux.go:259: applying cgroup configuration for process caused \"Cannot set property TasksAccounting, or unknown property.\""

**Comment by tantubufan** [comment]
git clone https://github.com/saleor/saleor-platform.git --recursive --jobs 3
error: unknown option `jobs'

**Comment by lkostrowski** [comment]
Hi, jobs is a part of git API. Maybe you have old version? 
https://git-scm.com/docs/git-clone#Documentation/git-clone.txt---jobsltngt

I think you can also remove this flag
