### ISSUE TITLE
Run github action to build this on each PR (after updated sumodules)

### ISSUE THREAD

**Issue by lkostrowski** [saleor/saleor-platform#161]
To avoid manual work after https://github.com/saleor/saleor-platform/pull/160 let's build container and run backend tests 

# AC

- CICD should trigger `docker-compose build`

**Comment by lkostrowski** [comment]
Another great idea from @magul is to run e2e tests. They will remove need of manual checks most likely. 

Calling @michalina-graczyk - what do you think about it? How complex it can be?

**Comment by michalina-graczyk** [comment]
I think that we can run Cypress test, as we do in dashboard. The critical tests are running on each PR, all results we could see in cypress-dashbaord.
