### ISSUE TITLE
Prepare update of submodules, including breaking change in docker-compose

### ISSUE THREAD

**Issue by lkostrowski** [saleor/saleor-platform#164]
[react-storefront](https://github.com/saleor/react-storefront) now is merged with Checkout.

That makes platform not working, because docker-compose has wrong path.

- [x] Update storefront submodule and docker-compose.yml
- [x] Add documentation / readme section that breaking changes can be fixed with pulling new version

**Comment by guyathomas** [comment]
DO we know a short term fix to work around this?

**Comment by lkostrowski** [comment]
Hey @guyathomas 

Fix is most likely here https://github.com/saleor/react-storefront/pull/335

You can also try using saleor-platform with storefront with commit `f05b99255b8e3ac2a66cb9c5422e3ef17a3008d9` - before breaking changes there

**Comment by lkostrowski** [comment]
Storefront is updated.
Readme is updated here - https://github.com/saleor/saleor-platform/pull/179
