### ISSUE TITLE
react-storefront checkout functionality not working

### ISSUE THREAD

**Issue by Msalmanzafar** [saleor/saleor-platform#187]
in the section of checkout nothing happen even i enter all required data, maybe it is related to authentication

**Comment by deltacodepl** [comment]
Probably you need to check your phone number, or another field you filled, 
from what I can see, checkout doesn't throw any error in case when number is invalid, but freezes.

**Comment by Msalmanzafar** [comment]
![Screenshot from 2022-09-14 15-29-48](https://user-images.githubusercontent.com/16886138/190131149-2d08fcba-cdc0-433f-8212-307a8294003a.png)

@deltacodepl 
here is the screen shot, just taken after your replay, 
i fill all fields and press save

**Comment by lkostrowski** [comment]
Hi

Checkout is under heavy development so most likely your issue has been fixed already. Please re-open or add a new issue if you still face the problem https://github.com/saleor/react-storefront/issues
