### ISSUE TITLE
Insufficiant documentation to get Saleor up and running

### ISSUE THREAD

**Issue by azizmb** [saleor/saleor-platform#224]
Since the split of Saleor into the separate cart/checkout apps, this repo is no longer fully functional even after following the documentation. Specifically with regards to the checkout implementation.

I'm happy to help with adding the docs, if someone can guide me through how to get the whole flow up and running. Unfortunately, the individual documentations for both [saleor-app-checkout](https://github.com/saleor/react-storefront/blob/canary/apps/saleor-app-checkout/README.md) and [checkout-storefront](https://github.com/saleor/react-storefront/blob/canary/packages/checkout-storefront/README.md) both don't help much in this regard.

**Comment by peelar** [comment]
Hello @azizmb 👋 

After following the steps from [`saleor-platform` README.md](https://github.com/saleor/saleor-platform/blob/main/README.md#how-to-run-it), you end up with a functional Storefront + Checkout. What do you think is missing from the documentation? And do you mean the `saleor-platform` documentation or the Storefront / Checkout documentation?

**Comment by azizmb** [comment]
Hey @peelar 

With the latest version of saleor-platform, following the documentation, I still can't figure out how to configure the checkout webhooks in saleor, or configure the app. 

Trying to install the checkout app using the manifest url fails with:
![image](https://user-images.githubusercontent.com/212671/210062954-94987f11-afb9-4cad-95a5-fdea0322c712.png)

I can't seem to find anywhere in the documentation how to get this all working. My eventual aim, is to add support for my payment provider (Razorpay), but, first need to get it running locally.

Any direction here would be much appreciated.

Off topic, but is there a saleor discord?

**Comment by Uponn** [comment]
hey, I'm also stuck at this step, setting up an checkout app locally with the saleor-platform repo

**Comment by patrys** [comment]
Storefront is no longer part of the platform, so I'm closing this. Please report related problems in the project's repository.
