### ISSUE TITLE
docker build failure

### ISSUE THREAD

**Issue by Rahulkishanm** [saleor/saleor-platform#226]
I use python version Python 3.9.16
and pip 22.0.4
I use mac m1 chip

But when i run `docker-compose build`
after
```
git clone https://github.com/saleor/saleor-platform.git --recursive --jobs 3
cd saleor-platform
```
I get error

#0 36.37   × python setup.py egg_info did not run successfully.
#0 36.37   │ exit code: 1
#0 36.37   ╰─> [14 lines of output]
#0 36.37       Traceback (most recent call last):
#0 36.37         File "<string>", line 2, in <module>
#0 36.37         File "<pip-setuptools-caller>", line 34, in <module>
#0 36.37         File "/tmp/pip-install-jvt5dprp/measurement_da1d31b43c824b269b019776ef30842a/setup.py", line 4, in <module>
#0 36.37           setup(use_scm_version=True)
#0 36.37         File "/usr/local/lib/python3.9/site-packages/setuptools/__init__.py", line 152, in setup
#0 36.37           _install_setup_requires(attrs)
#0 36.37         File "/usr/local/lib/python3.9/site-packages/setuptools/__init__.py", line 147, in _install_setup_requires
#0 36.37           dist.fetch_build_eggs(dist.setup_requires)
#0 36.37         File "/usr/local/lib/python3.9/site-packages/setuptools/dist.py", line 806, in fetch_build_eggs
#0 36.37           resolved_dists = pkg_resources.working_set.resolve(
#0 36.37         File "/usr/local/lib/python3.9/site-packages/pkg_resources/__init__.py", line 777, in resolve
#0 36.37           raise VersionConflict(dist, req).with_context(dependent_req)
#0 36.37       **pkg_resources.ContextualVersionConflict: (sphinxcontrib.applehelp 1.0.3 (/tmp/pip-install-jvt5dprp/measurement_da1d31b43c824b269b019776ef30842a/.eggs/sphinxcontrib.applehelp-1.0.3-py3.9.egg), Requirement.parse('sphinxcontrib-applehelp'), {'sphinx'})**
#0 36.37       [end of output]
#0 36.37   
#0 36.37   note: This error originates from a subprocess, and is likely not a problem with pip.
#0 36.37 error: metadata-generation-failed
#0 36.37 
#0 36.37 × Encountered error while generating package metadata.
#0 36.37 ╰─> See above for output.

<img width="918" alt="Screenshot 2023-01-09 at 1 49 18 AM" src="https://user-images.githubusercontent.com/11585684/211217179-67890060-4f69-45b5-8a96-7cfcfa93bfe2.png">

**Comment by fattymeatpower** [comment]
I just got this running! I changed
`measurement==3.2.0` to `measurement==2.0.1`
in saleor/requirements_dev.txt

It seems to work as expected.

**Comment by fattymeatpower** [comment]
More here https://github.com/coddingtonbear/python-measurement/issues/75

**Comment by fattymeatpower** [comment]
Hi. It might be better to re-open this and let someone else close it, so that they know there's a problem

**Comment by Lumunix** [comment]
Hello, I have also encountered this same docker build issue. I can confirm that @fattymeatpower 's fix allows the docker build to complete successfully. It also fixed my build issue.
`measurement==3.2.0 to measurement==2.0.1`

**Comment by patrys** [comment]
Closing as this repository no longer builds everything from scratch and instead relies on the official Docker images.
