### ISSUE TITLE
Checkout app issues

### ISSUE THREAD

**Issue by Uponn** [saleor/saleor-platform#232]
### Summary

using the saleor-platform I've managed to install Checkout app using ngrok but unsure if it configuration issue or something else I keep on getting:
```
saleor-app-checkout          | saleor-app-checkout:start: { 'req.headers.origin': undefined }
saleor-app-checkout          | saleor-app-checkout:start: Error: connect ECONNREFUSED 127.0.0.1:443
saleor-app-checkout          | saleor-app-checkout:start:     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1278:16)
saleor-app-checkout          | saleor-app-checkout:start:     at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17) {
saleor-app-checkout          | saleor-app-checkout:start:   errno: -111,
saleor-app-checkout          | saleor-app-checkout:start:   code: 'ECONNREFUSED',
saleor-app-checkout          | saleor-app-checkout:start:   syscall: 'connect',
saleor-app-checkout          | saleor-app-checkout:start:   address: '127.0.0.1',
saleor-app-checkout          | saleor-app-checkout:start:   port: 443
saleor-app-checkout          | saleor-app-checkout:start: }
```
App works fine until I go into the Settings page in the Checkout app.
![Capture](https://user-images.githubusercontent.com/19715940/212950050-f61a8514-2a1a-4447-ad06-015723eaf809.PNG)

### Steps to reproduce

- Fresh copy of saleor-platform, only change I do is to downgrade the version of ```measurement``` since it resolves some issues with the build that there are currently present
- Run all the steps from the readme to setup saleor-platform
- tunnel 3001 port using ngrok: ```ngrok http 3001```
- install Checkout app in the dashboard
- go into Settings to setup payment methods

those are the steps I went over without setting up any env variables, am I missing something?

## System:
 - OS: Windows 10 10.0.19044
 - CPU: (12) x64 AMD Ryzen 5 3600 6-Core Processor
 - Memory: 83.70 MB / 15.95 GB
## Binaries:
 - Node: 16.15.0 - C:\Program Files\nodejs\node.EXE
 - Yarn: 1.22.18 - ~\AppData\Roaming\npm\yarn.CMD
 - npm: 8.11.0 - C:\Program Files\nodejs\npm.CMD
## Browsers:
 - Chrome: 109.0.5414.74
 - Edge: Spartan (44.19041.1266.0), Chromium (109.0.1518.55)
 - Internet Explorer: 11.0.19041.1566

pnpm --version: 7.25.0

**Comment by witoszekdev** [comment]
Hi, for local development, you'd need to tunnel both:
 - the app [`saleor-app-checkout`](https://github.com/saleor/react-storefront/tree/436ac1328af2fbe784890969efb6bc1d9eb1c573/apps/saleor-app-checkout) (like you did by using our [CLI tool](https://github.com/saleor/saleor-cli): `saleor app tunnel 3001`)
 - your local Saleor instance (you could use [ngrok](https://ngrok.com/) for that: `ngrok http 8000`)

Once both the app and Saleor are accessible from the Internet, you'll have to:
 1. Change the [`SALEOR_API_URL`](https://github.com/saleor/react-storefront/blob/canary/docs/development.md#env-variables) env variable inside the `.env` file to the URL of your tunneled Saleor instance (e.g. `https://1234.eu.ngrok.io/graphql/`)
 2. Update [`ALLOWED_HOSTS`](https://docs.saleor.io/docs/3.x/setup/configuration#allowed_hosts) env variable in Saleor to include ngrok tunnel URL. In case of `saleor-platfrom` you'd have to update the [`docker-compose.yaml` file](https://docs.docker.com/compose/environment-variables/#set-environment-variables-in-containers). It would look something like this:
```yaml
services:
  api:
    # ...
    environment:
      - JAEGER_AGENT_HOST=jaeger
      - STOREFRONT_URL=http://localhost:3000/
      - DASHBOARD_URL=http://localhost:9000/
      - ALLOWED_HOSTS=localhost,api,1234.eu.ngrok.io # <-- add tunnel domain here
```

When you do all that, restart both the app in `react-storefront` repository (`npm run dev`) and Saleor in Docker Compose (`docker compose down && docker compose up -d api worker`).

If you don't want to deal with creating a local Saleor instance, you could create a free sandbox instance in Saleor Cloud instead:

```
saleor storefront create --demo
```

In case you have more issues with the app, please refer to the documentation [inside the repository](https://github.com/saleor/react-storefront/blob/canary/docs/faq.md) or create a [new issue on GitHub](https://github.com/saleor/react-storefront/issues).

I hope that helps :)

**Comment by patrys** [comment]
Storefront is no longer part of the platform, so I'm closing this. Please report related problems in the project's repository.
