### ISSUE TITLE
Some error and warning logs when navigating to the checkout page

### ISSUE THREAD

**Issue by hqlinh796** [saleor/saleor-platform#233]
![Screen Shot 2023-02-01 at 11 01 26 PM](https://user-images.githubusercontent.com/42135412/216097798-65fdaf68-512d-45a0-b54b-c5cc0965617f.png)
I saw some errors and warnings when navigating to the checkout page. Then, when I clicked the pay button, nothing happened.

**Steps to produce**

- Add a product to the cart
- Click the cart button on the nav bar
- Redirect to the checkout page
- Open dev tool and check the logs

**Comment by patrys** [comment]
Storefront is no longer part of the platform, so I'm closing this. Please report related problems in the project's repository.
