### ISSUE TITLE
Official docker images should be advertised more

### ISSUE THREAD

**Issue by gempain** [saleor/saleor-platform#236]
Hi there 👋 
Thanks so much for this repository, and all the ecosystem around this amazing product.
While going through setup and deployment, I realized after quite a few hours that you have official images published on the [Github Container Registry](https://github.com/saleor/saleor/pkgs/container/saleor).
The only reference to these images I could find is [here](https://docs.saleor.io/docs/3.x/setup/docker-images) in the docs. I think it would be beneficial to emphasize the existence of these images in this repository, which is the main source advertized on the official saleor repository, website and documentation.
Keep up the great work!

**Comment by patrys** [comment]
Related: #238

**Comment by patrys** [comment]
Closing this as we're finally using official images!
