### ISSUE TITLE
I can't open STOREFRONT and DASHBOARD (graphql loaded from localhost:8000/graphql

### ISSUE THREAD

**Issue by spacewalkingninja** [saleor/saleor-platform#241]
Hello!
I've configured myself a VM on Google cloud and I ran the docker compose build instructions. 
Latest release.
Problem is identical to:
https://github.com/saleor/saleor/issues/6580
AND
https://github.com/saleor/saleor-platform/issues/125
AND
https://github.com/saleor/saleor/discussions/8293 

Hence:
API_URI is required to avoid:
![image](https://user-images.githubusercontent.com/27017759/218817044-bca90e5d-7f7c-483c-a634-b4f8cf1d66d1.png)

I got the CORRECT API_URI in saleor-platform/docker-compose.yml and also set up a API_NEXT_PUBLIC_URL or whatever the var name.
I will test now doing this:

-    command: npm start -- --host 0.0.0.0
+    command: npm start -- --host 0.0.0.0 --disable-host-check

I'm really at a loss as to what to do so I can test. I want to test on a machine as close as possible to prod. enviroment, so I must do it on a google cloud VM and expose the API smh (also can I https it with certbot? I'm coming from thirtybees and apache so I'm not really sure as to the workflow) 

EDIT1:
Im currently in ./react-storefront/docker-compose.yml  and this is the changes:
  ```
  command: npm start -- --host 0.0.0.0 --disable-host-check --filter=storefront...
#    command: sh -c '(nginx &) && pnpm turbo run start --filter=storefront...'
    environment:
      - NEXT_PUBLIC_API_URI=http://s.domain.com:8000/graphql/
      - API_URI=http://s.domain.com:8000/graphql/
      - NEXT_PUBLIC_API_URL=http://s.domain.com:8000/graphql/
      - API_URL=http://s.domain.com:8000/graphql/
```
EDIT2 
Apparently " command: npm start -- --host 0.0.0.0 --disable-host-check --filter=storefront..." BREAKS IT. 
Ideas? 
**_I AM ON MY KNEES AND I BEG FOR YOUR HELP TO SOLVE THIS ISSUE AS I DESCRIBED IT._**

**Comment by spacewalkingninja** [comment]
Guys, I've been GREP and ACKing to brute force this localhost graphql thing, please just provide a S/I/M/P/L/E Solution so people like me can work on this system on a remote server with open ports we can access via the browser. Would be VERY VERY VERY VERY VERY VERY VERY thanks <3

**Comment by patrys** [comment]
If you are using the `main` branch of core, it could be because of a missing CORS header in our new CORS implementation: https://github.com/saleor/saleor/pull/12038

**Comment by spacewalkingninja** [comment]
@patrys I don't believe this is the problem. My problem is that even when I compile it with API_URL and NEXT_PUBLIC_API_URL set to my server.domain.com:8000/graphql/ when I open (for example) the storefront, it loads but I get errors as It still tries to load localhost:8000/graphql/  instead of server.domain.com:8000/graphql/

**Comment by patrys** [comment]
I am unsure what exactly you're trying to edit, but Saleor itself is not meant to be edited. We provide APIs for extensibility. The updated `saleor-platform` repository no longer builds any images and instead relies on official Docker images. It should work for you without additional tweaks, allowing you to focus on satellite services such as the storefront, checkout, and any custom integrations you plan to create.
