### ISSUE TITLE
Metadata not getting saved while create checkout

### ISSUE THREAD

**Issue by tanujrawat95** [saleor/saleor-platform#243]
Hello everyone!
I am trying to save some metadata field in db while creating checkout. There is option to pass metadata in graphql query, it is getting passed to the backend without any issue, but fetching and saving the metadata is not handled in the backend as per my knowledge.
One solution would be to override the current method to handle this case. But before that I want to make sure i am doing everything correct and not missing anything.

I am sending this variable data to query to create checkout
`{"channel": "default-channel","email": "abc@gmail.com","lines": [{"quantity": 1, "variantId": "UHJvZHVjdFZhcmlhbnQ6MzQ2","metadata": [{"key": "Form","value":"Neww data"}]}]}`

metadata is getting passed inside "lines" key.

The code that is handling it is in saleor -> graphql -> core -> mutations.py -> class ModelMutation -> def clean_input()

Please let me know the possible solution for it.

**Comment by patrys** [comment]
If you can still reproduce it with the latest version of `saleor-platform`, please open a ticket in [the core repository](https://github.com/saleor/saleor).
