### ISSUE TITLE
Cannot create super user in when installing with docker

### ISSUE THREAD

**Issue by Raam124** [saleor/saleor-platform#245]
I just cloned and tried the commands to run according to the docs. migrations and populatedb work fine but when I tried to create a super user it throws the below error.  I can run the application with docker-compose but cannot create a super user

branch - 3.10.1

cmd : `docker-compose run --rm api python3 manage.py createsuperuser`

error: 
![Screenshot from 2023-02-22 18-17-04](https://user-images.githubusercontent.com/46324509/220623852-38908405-b6f8-427a-a775-60841cec6feb.png)

**Comment by patrys** [comment]
Can you test the current `saleor-platform`? We just switched it to use Docker images instead of building everything from scratch using git submodules.
