### ISSUE TITLE
nothing shows up on port 3001 after docker compose up

### ISSUE THREAD

**Issue by qrukru** [saleor/saleor-platform#263]
http://localhost:8000/ and http://localhost:9000/ show up successfully but port 3001.
I have read that "If nothing shows up on port 3001 or 9000, wait until Compiled successfully shows in the console output."
But I could only find things like below in powershell:
"
saleor-platform-mailhog-1    | [APIv1] KEEPALIVE /api/v1/events
saleor-platform-mailhog-1    | [APIv1] KEEPALIVE /api/v1/events
saleor-platform-mailhog-1    | [APIv1] KEEPALIVE /api/v1/events
saleor-platform-mailhog-1    | [APIv1] KEEPALIVE /api/v1/events
saleor-platform-mailhog-1    | [APIv1] KEEPALIVE /api/v1/events
"
is storefront still provided on port 3001?

**Comment by qrukru** [comment]
I check port use with "netstat -ano" on cmd.
It seems port3000 is not used, both the status on docker desktop Running(7/7)

**Comment by qrukru** [comment]
I check port use with "netstat -ano" on cmd.
It seems port3001 is not used(no results show with 0.0.0.0:3001), both all ports checked in the status on docker desktop Running(7/7).
I wonder if some upgrade made storefront isn't provided by saleor-platform anymore...

**Comment by qrukru** [comment]
I check port use with "netstat -ano" on cmd.
It seems port3001 is not used(no results show with 0.0.0.0:3001), both ports in the status on docker desktop Running(7/7) .
I wonder if some upgrade made storefront isn't provided by saleor-platform anymore...

**Comment by jukafah** [comment]
I just ran into this yesterday. Does saleor-platform still provide the storefront?

**Comment by jukafah** [comment]
I looked at the history and did find that they decided to remove it in #238

**Comment by qrukru** [comment]
> 

thks, so some "step-by-step installation and deployment instructions" should be change.
