### ISSUE TITLE
after docker-compose down & docker-compose up again, the front end always show 404 pages

### ISSUE THREAD

**Issue by david-daming** [saleor/saleor-platform#28]
Hi,

I run command `docker-compose down` to shutdown all the containers. If I start the containers again with command `docker-compose up`, all the containers were started successfully, but I keep on meeting with the 404 page for every frontend page I accessed.

check on the log it says:
`Failed to load resource: the server responded with a status of 404 (Not Found)`

Do I have to rebuild the containers every time before I start?

**Comment by david-daming** [comment]
Here is my docker container status:

david@DaMings-MacBook-Pro saleor-platform % docker-compose ps
           Name                        Command             State             Ports
---------------------------------------------------------------------------------------------
saleor-platform_api_1         python manage.py runserver   Up      0.0.0.0:8000->8000/tcp
                              ...
saleor-platform_dashboard_1   docker-entrypoint.sh npm s   Up      0.0.0.0:9000->9000/tcp
                              ...
saleor-platform_db_1          docker-entrypoint.sh         Up      0.0.0.0:5432->5432/tcp
                              postgres
saleor-platform_jaeger_1      /go/bin/all-in-one-linux -   Up      14250/tcp,
                              ...                                  0.0.0.0:14268->14268/tcp,
                                                                   0.0.0.0:16686->16686/tcp,
                                                                   0.0.0.0:5775->5775/udp,
                                                                   0.0.0.0:5778->5778/tcp,
                                                                   0.0.0.0:6831->6831/udp,
                                                                   0.0.0.0:6832->6832/udp,
                                                                   0.0.0.0:9411->9411/tcp
saleor-platform_redis_1       docker-entrypoint.sh redis   Up      0.0.0.0:6379->6379/tcp
                              ...
saleor-                       docker-entrypoint.sh npm s   Up      0.0.0.0:3000->3000/tcp
platform_storefront_1         ...
saleor-platform_worker_1      celery -A saleor worker --   Up      8000/tcp

**Comment by maarcingebala** [comment]
Hey, it shouldn't happen normally, but you're getting such strange issues or build errors you can try to rebuild the containers: https://github.com/mirumee/saleor-platform#how-to-solve-issues-with-lack-of-available-space-or-build-errors-after-update

**Comment by jinhojang6** [comment]
I have the same error when I run containers for a long time, `dock-compose down`, and `dock-compose up` again

**Comment by krzysztofwolski** [comment]
Are you sure you gave enough time for frontends to build? By default, they start up with dev mode, which takes time to start up

**Comment by maltitco** [comment]
@david-daming If you see Compiled successfully in the console should be ok, and then try to clear the cache in your browser or use incognito mode.
