### ISSUE TITLE
Docker build on Raspberry Pi error

### ISSUE THREAD

**Issue by blackyzero** [saleor/saleor-platform#46]
Hi,

i got issue with docker-compose on raspberri 4 - 8G ram,
How could i fix it? Thanks a lot.

`Digest: sha256:2570ba0fc206d0ef13dfb5563c8b93e5cf8a4cc7b1136dcab1de6466da8a3e91
Status: Downloaded newer image for node:10
 ---> 66001491656e
Step 2/9 : WORKDIR /app
 ---> Running in 19693c86e34d
Removing intermediate container 19693c86e34d
 ---> d2eb206851c0
Step 3/9 : COPY package*.json ./
 ---> ebb23e92bfac
Step 4/9 : RUN npm install
 ---> Running in 1c1649c67b35
Aborted (core dumped)
ERROR: Service 'storefront' failed to build: The command '/bin/sh -c npm install' returned a non-zero code: 134
root@ubuntu:/opt/services/saleor-platform#`

**Comment by NyanKiyoshi** [comment]
Hi,

I don't know about what's up with the storefront build (not enough logs attached in your post). But what I can tell for core (the GraphQL API) is that we don't ship ARM64 support at the moment. Unless there is a request for it, we are not planning at the moment to add ARM64 support.
