### ISSUE TITLE
ERROR: Cannot locate specified Dockerfile: ./Dockerfile.dev

### ISSUE THREAD

**Issue by kevincf** [saleor/saleor-platform#54]
Hi, when running docker-compose o get this error "Cannot locate specified Dockerfile: ./Dockerfile.dev"
I am working in a machine with ubuntu 20.04 with "Docker version 19.03.12, build 48a66213fe
"

**Comment by RancellTapia** [comment]
> Hi, when running docker-compose o get this error "Cannot locate specified Dockerfile: ./Dockerfile.dev"
> I am working in a machine with ubuntu 20.04 with "Docker version 19.03.12, build 48a66213fe
> "

Hi! 

Check if the saleor-dashboard folder has a file, otherwise you will have to clone each of the repositories separately.

**Comment by AhmadManzoor** [comment]
this issue is related to docker-compose.yml.
in react-storefront: section
replace this line 
```
      context: ./saelor-storefront
```
with
`      context: ./react-storefront
`

**Comment by magul** [comment]
Ok, so assuming that this ticket was created in July 2020 there were no `react-storefront` then.

My assumption, what happened back then was (correct me if I'm wrong @kevincf ).

This repository contains (and contained back then) 3 git submodules, these submodules themselves contains `Dockerfile`s used for building images. If you don't initialize these submodules, there will be no files in these directories, for `docker-compose` will not find them.

In our `README.md` we have a command `git clone https://github.com/saleor/saleor-platform.git --recursive --jobs 3`, which, when run will initialize this root repo and all submodules recursively, without `--recursive` you have to initilize these submodules manually. (this `--recusive` was added to our README in February 2020, removing that manual step of fetching submodules after clone of root repository, see: https://github.com/saleor/saleor-platform/commit/99c9eded6720c0607371dd7afe0ad1c59b96b307).

My hypothesis is that you just simply cloned this repo, forgetting to initilize submodules.

Nothing that we can help here, unless you provide additional informations that will be invalidate my hypothesis.
