### ISSUE TITLE
storefront fail to run after fresh build

### ISSUE THREAD

**Issue by chapp-hk** [saleor/saleor-platform#61]
**steps to reproduce:**

1. clone the repository and submodules

1. follow steps to build, migrate, populate database and start

1. wait for build finish

1. go to http://localhost:3000

**expected:** storefront web interface shows

**actual:** blank page shown with error in console
<img width="1532" alt="Screenshot 2020-07-30 at 21 04 19" src="https://user-images.githubusercontent.com/17695286/88926312-6770b600-d2a8-11ea-96e9-314965655b02.png">

**Comment by rasovica** [comment]
Same problem here

**Comment by psdon** [comment]
same here

**Comment by krzysztofwolski** [comment]
Issue will be adressed in upcoming release
