### ISSUE TITLE
Unable to install with docker compose

### ISSUE THREAD

**Issue by pupattan** [saleor/saleor-platform#66]
While installing / building with docker compose i am facing this issue 
The command '/bin/sh -c npm install' returned a non-zero code: 137

```
# docker-compose build
db uses an image, skipping
redis uses an image, skipping
jaeger uses an image, skipping
mailhog uses an image, skipping
Building storefront
Step 1/9 : FROM node:10
10: Pulling from library/node
419e7ae5bb1e: Pull complete
848839e0cd3b: Pull complete
de30e8b35015: Pull complete
258fdea6ea48: Pull complete
ddb75eb7f1e9: Pull complete
7ec8a0667334: Pull complete
7fb55a10000f: Pull complete
e7fe95591c34: Pull complete
a1fc4c64e548: Pull complete
Digest: sha256:cf3ee6a5a1b1916c7a2e4fb51eb7ecba1afe186739677d62e9c1bb2cb1c7d6b0
Status: Downloaded newer image for node:10
 ---> 5ebbf4bb3837
Step 2/9 : WORKDIR /app
 ---> Running in f5967c6f3f99
Removing intermediate container f5967c6f3f99
 ---> 0bb50bea4675
Step 3/9 : COPY package*.json ./
 ---> 9c6ad499b135
Step 4/9 : RUN npm install
 ---> Running in 263954e03470
Killed
ERROR: Service 'storefront' failed to build: The command '/bin/sh -c npm install' returned a non-zero code: 137
```

**Comment by tburd** [comment]
@pupattan 
I am facing the same issue. Have you found a solution so far?

**Comment by tburd** [comment]
> @pupattan
> I am facing the same issue. Have you found a solution so far?

The internet is lovely :)
I had to upgrade my VS to overcome this problem....
I am using Digital Ocean droplet:

> **Started with**:   1vCPU / 1GB Ram: **FAILED**
> **Upgreated to**: 1vCPU / 2GB Ram: **FAILED**
> **Upgreated to**: 2vCPU / 2GB Ram: **FAILED**
> **Upgreated to**: 2vCPU / 4GB Ram: **SUCCESS**

**Comment by balibebas** [comment]
Ouch. [Reaction Commerce](https://reactioncommerce.com) runs on only 2GB RAM.

**Comment by balibebas** [comment]
Ouch. [Reaction Commerce](https://reactioncommerce.com) runs on only 2GB RAM. The admin isn't pretty but the storefront sure is.

**Comment by marklegend** [comment]
Sorry to add to this, but if anyone knows how to pass this?


![Screenshot from 2021-02-06 03 35 03](https://user-images.githubusercontent.com/43289512/107104883-5773f900-682c-11eb-8902-15a5c1b6fe67.png)

**Comment by proalaa** [comment]
I'm facing the same problem 

any solution ?

**Comment by marklegend** [comment]
no, I went with installing it on my system directly, installed and configured my system for example installed all the dev tools needed, node.js, python, pip and etc... to make it run without docker but it was a long time ago

**Comment by hmtanbir** [comment]
I'm facing the same problem

any solution?

**Comment by lkostrowski** [comment]
Hi, projects have been updated a lot, please fetch new saleor-platform or update specific submodules, most likely its fixed
