### ISSUE TITLE
DB container keeps restarting

### ISSUE THREAD

**Issue by d-eisenga** [saleor/saleor-platform#71]
I'm following the steps in the readme, but I run into an issue at step 5 (apply Django migrations). It starts 3 containers (db, redis, jaeger), then logs an error: `psycopg2.OperationalError: could not translate host name "db" to address: Name or service not known`.

Listing my containers with `docker-compose ps`, I can see that the db containers is always in the `Restarting` state. Checking the logs of that container, I see the following repeated over and over, about every minute:

```
The files belonging to this database system will be owned by user "postgres".
This user must also own the server process.

The database cluster will be initialized with locale "en_US.utf8".
The default database encoding has accordingly been set to "UTF8".
The default text search configuration will be set to "english".

Data page checksums are disabled.

initdb: directory "/var/lib/postgresql/data" exists but is not empty
If you want to create a new database system, either remove or empty
the directory "/var/lib/postgresql/data" or run initdb
with an argument other than "/var/lib/postgresql/data".
```

What am I doing wrong? Am I skipping a step? I'm on Linux Mint 20, for what it's worth.

**Comment by KonstantinosPapadopoulos** [comment]
Hi - did you find a solution to that? I'm having the same problem

**Comment by d-eisenga** [comment]
I'm afraid not, I'm now just trying to run the 3 apps individually, but as you can imagine it's not as quick and convenient.

**Comment by KonstantinosPapadopoulos** [comment]
Ah I see thank you very much I'll try that

**Comment by d-eisenga** [comment]
So this issue has been closed - has the problem been fixed in the current release?

**Comment by serranomorante** [comment]
I'm facing this issue right now. Solved it by following [this](https://stackoverflow.com/a/58146616/10395099)
