### ISSUE TITLE
Broken link to docs at splash screen at localhost:8000

### ISSUE THREAD

**Issue by denn-massalitin** [saleor/saleor-platform#72]
On splash screen at localhost:8000 there is link to docs at the top-right corner.

"[View documentation ](https://docs.saleor.io/docs/index/)for Saleor 2.10"
Link now is: https://docs.saleor.io/docs/index/

Correct Link : https://docs.saleor.io/docs/

![Screenshot (17)](https://user-images.githubusercontent.com/72509409/95377096-bfe8b300-08ea-11eb-8b53-ab92bb519a53.png)

**Comment by krzysztofwolski** [comment]
Thank you for the report - patch submitted https://github.com/saleor/saleor/pull/9437
