### ISSUE TITLE
[question] How to manage Git fork

### ISSUE THREAD

**Issue by crisfcodes** [saleor/saleor-platform#87]
I want to take the `API` and the `Dashboard`, for the `Storefront`, I will develop it from zero with react native, my question is, how do I manage this on git:  

1. I make a fork of `saleor-platform` repository, remove the storefront and create another repository with my custom storefront and include it as a submodule?
2. Fork individually each of the repositories that I need (`Dashboard` and `API`) and I clone them on my machine and simply create my own storefrond repository and put aside the other ones. In this case what happend with parent `saleor-paltform` files like `docker-compose.yml`.

### Other associated questions

1. Why use submodules and why not subtrees?
2. What is the recommended road according to Saleor to manage this kind of scenarios on git. Where I just want to get some modules(`API` and `Dashboard`) and keep them updated with changes made by the source repository, and do the rest myself(Storefront) and mantain that repository on my side.

Why use `submodules` and why not subtress?

**Comment by h-2-0** [comment]
I second your second associated question (no pun intended)

_What is the recommended road according to Saleor to manage this kind of scenarios on git_

Or, in general, what are people doing here in terms of git setup and flow.

**Comment by qfunq** [comment]
I'm using git clone --bare --mirror for each repo, and editing the config file to point to the new repos. This works as a new recursive git, which can be pushed to, and pulled from.

With this relatively simple setup (emulating the missing git clone --bare --mirror --recurse-submodules), it is possible to fetch any upstream changes (and cope with any merges). In principal, it's possible to fork each repo, then bare mirror them, re populate the recursive structure and push it all back to the fork. It's quite a lot of work to emulate git fork --bare --mirror --recurse-submodules, unless I am missing something obvious.

I've only just started with the clone --bare --mirror setup, so there are bound to be teething issues, but it's passing local CRUD tests, bar no updates have occurred upstream to test against!

**Comment by qfunq** [comment]
... on the other hand, in an ideal world, all saleor development is done using apps, plugins, metadata and runtime environment, so it's best to design accordingly?

**Comment by patrys** [comment]
Platform now relies only on official Docker images. This should make keeping up with Saleor releases much easier.
