### ISSUE TITLE
? Command failed: /app/node_modules/cwebp-bin/vendor/cwebp -version

### ISSUE THREAD

**Issue by auvipy** [saleor/saleor-platform#91]
? Command failed: /app/node_modules/cwebp-bin/vendor/cwebp -version
/app/node_modules/cwebp-bin/vendor/cwebp: error while loading shared libraries: libGL.so.1: cannot open shared object file: No such file or directory

  ? cwebp pre-build test failed
  ? compiling from source
  ? cwebp built successfully

**Comment by krzysztofwolski** [comment]
Could not reproduce with the current version.
