### ISSUE TITLE
Docker: storefront and dashboard throw NPM errors, but others work fine

### ISSUE THREAD

**Issue by Megidd** [saleor/saleor-platform#95]
# Installation

Followed [installation guide](https://docs.saleor.io/docs/developer/installation/) by installing and running Docker Desktop (Windows 10) and executing these commands:

```
git clone https://github.com/mirumee/saleor-platform.git --recursive --jobs 3
cd saleor-platform
docker-compose build
docker-compose run --rm api python3 manage.py migrate
docker-compose run --rm api python3 manage.py collectstatic --noinput
docker-compose run --rm api python3 manage.py populatedb
docker-compose run --rm api python3 manage.py createsuperuser
docker-compose up
```

# API (backend): good

Backend API works fine on port `8000`:

![image](https://user-images.githubusercontent.com/17475482/116646575-ab0a6480-a98d-11eb-926e-97f54233795c.png)

# Storefront and dashboard: NPM errors

But storefront and dashboard throw errors:

![image](https://user-images.githubusercontent.com/17475482/116646653-dbea9980-a98d-11eb-8c88-087e265c99a5.png)

![image](https://user-images.githubusercontent.com/17475482/116646694-fcb2ef00-a98d-11eb-8e48-2ae0f10eac9e.png)

![image](https://user-images.githubusercontent.com/17475482/116646738-15230980-a98e-11eb-9706-f0989d15d00c.png)

# Storefront error log

```
storefront_1  |
storefront_1  | > saleor-site@2.11.0 start /app
storefront_1  | > cross-env NODE_ENV=develop webpack-dev-server --history-api-fallback --watch --port 3000 --mode development --hotOnly "--hostname" "0.0.0.0"
storefront_1  |
storefront_1  | sh: 1: cross-env: not found
storefront_1  | npm ERR! code ELIFECYCLE
storefront_1  | npm ERR! syscall spawn
storefront_1  | npm ERR! file sh
storefront_1  | npm ERR! errno ENOENT
storefront_1  | npm ERR! saleor-site@2.11.0 start: `cross-env NODE_ENV=develop webpack-dev-server --history-api-fallback --watch --port 3000 --mode development --hotOnly "--hostname" "0.0.0.0"`
storefront_1  | npm ERR! spawn ENOENT
storefront_1  | npm ERR!
storefront_1  | npm ERR! Failed at the saleor-site@2.11.0 start script.
storefront_1  | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
storefront_1  | npm WARN Local package.json exists, but node_modules missing, did you mean to install?
storefront_1  |
storefront_1  | npm ERR! A complete log of this run can be found in:
storefront_1  | npm ERR!     /root/.npm/_logs/2021-04-30T03_31_03_452Z-debug.log
saleor-platform_storefront_1 exited with code 1
```

# Dashboard error log

```
dashboard_1   |
dashboard_1   | > saleor-dashboard@2.11.0 start /app
dashboard_1   | > webpack-dev-server -d "--host" "0.0.0.0"
dashboard_1   |
dashboard_1   | sh: 1: webpack-dev-server: not found
dashboard_1   | npm ERR! code ELIFECYCLE
dashboard_1   | npm ERR! syscall spawn
dashboard_1   | npm ERR! file sh
dashboard_1   | npm ERR! errno ENOENT
dashboard_1   | npm ERR! saleor-dashboard@2.11.0 start: `webpack-dev-server -d "--host" "0.0.0.0"`
dashboard_1   | npm ERR! spawn ENOENT
dashboard_1   | npm ERR!
dashboard_1   | npm ERR! Failed at the saleor-dashboard@2.11.0 start script.
dashboard_1   | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
dashboard_1   | npm WARN Local package.json exists, but node_modules missing, did you mean to install?
dashboard_1   |
dashboard_1   | npm ERR! A complete log of this run can be found in:
dashboard_1   | npm ERR!     /root/.npm/_logs/2021-04-30T03_31_08_589Z-debug.log
saleor-platform_dashboard_1 exited with code 1
```

**Comment by prashantidealittechno** [comment]
For me, frontend works but the website is not up I tried it 3 times after remove all volumes and images via `docker system prune -a` and `docker system prune --volumes`

**Comment by Megidd** [comment]
@prashantidealittechno 

### Observations

Windows Docker tested a couple of days ago:

* Backend API was fine
* Dashboard threw NPM errors
* Storefront threw NPM errors

Linux Docker tested yesterday:

* Backend API is fine
* Dashboard is fine
* Storefront throws NPM warnings and doesn't load the storefront website

**Comment by ptmew** [comment]
I also have a problem with my Linux. I found that changing the argument of the frontstore service in docker-compose.yaml from --hostname to --host resolve this problem.

**Comment by Megidd** [comment]
As hinted by @ptmew , such a commit resolved the storefront issue on Linux:

```
diff --git a/docker-compose.yml b/docker-compose.yml
index c53b920..ac34d90 100644
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -39,7 +39,9 @@ services:
     volumes:
       - ./saleor-storefront/:/app:cached
       - /app/node_modules/
-    command: npm start -- --hostname 0.0.0.0
+    command: npm start -- --host 0.0.0.0
```
Now the storefront is available at http://localhost:3000

![image](https://user-images.githubusercontent.com/17475482/118356281-a21eb300-b589-11eb-9ab9-bf1560f350c5.png)

I don't care about Windows anymore. So, I cannot test on the Windows platform.

**Comment by Megidd** [comment]
@ptmew Just curious, how did you figure out to replace `--hostname` with `--host`? Did you just randomly do trial-and-error? Did you have any hint from somewhere? What was your research process? Thanks!

**Comment by tyrozz** [comment]
I got the same issue. I followed the exact steps in saleor-platform repo, the api and the dashboard were just working fine, but the storefront. I also changed from --hostname to --host and it worked. Actually in the docker-compose, it is also like this for the dashboard.

**Comment by krzysztofwolski** [comment]
Issue resolved

**Comment by tauseedzaman** [comment]
> hos

![image](https://github.com/saleor/saleor-platform/assets/64689921/197ef469-aa67-402b-b737-59f28b4015be)

this is running via docker and configured on a domain.. but this api is running on a localhost on a server... any idea what wrong ?
